version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  rust_app:
    build: .
    container_name: rust_app
    ports:
      - "8090:8090"
    depends_on:
      - db
volumes:
  postgres-data: